import type { BuildingDefInput } from '@odal/engine';

export const buildings: BuildingDefInput[] = [
  {
    id: 'campfire',
    name: 'Campfire',
    desc: 'The heart of the village. Trains workers and receives harvested resources.',
    buildable: false,
    time: 0,
    hp: 200,
    size: { w: 1, h: 1 },
    pop: 5,
    trains: ['worker'],
    dropOff: true,
    vision: 9,
    visual: { shape: 'cone', color: '#ff6f1f', height: 0.8, glow: '#ff4500' },
  },
  {
    id: 'house',
    name: 'House',
    desc: '+5 population.',
    cost: { lumber: 25 },
    time: 15,
    hp: 150,
    size: { w: 1, h: 1 },
    pop: 5,
    hotkey: 'H',
    visual: { color: '#8d6e63', height: 1.2 },
  },
  {
    id: 'farm',
    name: 'Farm',
    desc: 'Grows 4 wheat every 8 seconds.',
    cost: { lumber: 20 },
    time: 15,
    hp: 100,
    size: { w: 2, h: 2 },
    produces: { resource: 'wheat', amount: 4, interval: 8 },
    hotkey: 'F',
    visual: { color: '#d4b04a', height: 0.25 },
  },
  {
    id: 'library',
    name: 'Library',
    desc: 'Researches technology.',
    cost: { lumber: 40, gold: 10 },
    time: 25,
    hp: 200,
    size: { w: 2, h: 2 },
    researches: ['ironworking', 'sharp_axes', 'crop_rotation', 'steel_weapons'],
    hotkey: 'L',
    visual: { color: '#7e57c2', height: 1.6 },
  },
  {
    id: 'barracks',
    name: 'Barracks',
    desc: 'Trains soldiers.',
    cost: { lumber: 50, iron: 20 },
    time: 30,
    hp: 300,
    size: { w: 2, h: 2 },
    trains: ['soldier'],
    requires: [{ type: 'tech', id: 'ironworking' }],
    hotkey: 'B',
    visual: { color: '#9c2f2f', height: 1.4 },
  },
];
